# wrangler.toml
name = "chat-server"
main = "index.js"

[[durable_objects.bindings]]
name = "CHAT_SERVER"
class_name = "ChatServer2"

[[migrations]]
tag = "v1"
new_classes = ["ChatServer2"]

[env.variables]
ADMIN_LIST = "admin1,admin2"
