 name = "chatcloudflare"
main = "index.js"
compatibility_date = "2024-12-18"

[[durable_objects.bindings]]
name = "CHAT_SERVER_2"
class_name = "ChatServer2"

# TIDAK perlu migrations karena tidak pakai storage SQLite
